"use client";

import { AppShell } from "@/components/layout/AppShell";
import { RealtimeTable } from "@/components/tables/RealtimeTable";
import { qIssues } from "@/lib/queries";
import { useCollectionSource } from "@/lib/useDataSource";
import type { DataQualityIssue } from "@/lib/types";

const columns = [
  { key: "severity", label: "Severity" },
  { key: "category", label: "Category" },
  { key: "sourceKey", label: "Source" },
  { key: "sourceRow", label: "Row" },
  { key: "sourceField", label: "Field" },
  { key: "issueDescription", label: "Issue" },
  { key: "evidenceType", label: "Evidence type" },
  { key: "evidence", label: "Evidence" },
  { key: "recommendedFix", label: "Recommended fix" },
  { key: "status", label: "Status" }
];

export function DataQualityPage() {
  const { data } = useCollectionSource<DataQualityIssue>("data_quality_issues", qIssues());
  return (
    <AppShell>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-900">Data Quality</h1>
        <p className="text-sm text-slate-500">Open issues generated by validators. Sensitive evidence is masked.</p>
      </div>
      <RealtimeTable rows={data} columns={columns} />
    </AppShell>
  );
}
